### PR TITLE
implemented AWS requirements

### PR DESCRIPTION
**Pull request by IvanProdaiko94**
Hi, everyone) Could someone please take a look at this draft?

How to use it:

#### Building the backend with TLS support:

 1) `go get -u github.com/go-bindata/go-bindata/...` - downloading the bindata package
2) Place your tls certificate and tls key into `./backend/creds` folder
3) `cd ./backend && go-bindata -o assets.go ./creds` - move credentials files as a `.go` files
4) `go build -i -ldflags "-X main.CertPath=/creds/cert_file_name -X main.KeyPath=/creds/key_file_name -X main.InsecureSkipVerify=true" -o ./dist/cassandra-plugin_linux_amd64 ./backend` - build binary with required variables filled in. 
   If you'd like to use rootCA, do `go build -i -ldflags "-X main.RootCA=/creds/root_ca_file_name" -o ./dist/cassandra-plugin_linux_amd64 ./backend`

P.S. as a part of the PR `go fmt` applied

### CODE REVIEW

**Comment by futuarmo** [comment]
Hi, thank you for pull request) I'll watch it today. Did you build it locally (without docker)?

**Comment by IvanProdaiko94** [comment]
@futuarmo yeah, the last command in the description wasn't right. fixed

**Comment by HadesArchitect** [comment]
What's the issue with the tests? We should change the backend dependencies build step, should we?

**Comment by futuarmo** [comment]
Looks good, but we must to integrate your changes with Docker and then we'll merge PR 🙂 I'll try it later today

**Comment by futuarmo** [comment]
I get the same error as github actions - grafana-plugin-model/go/datasource not found, but can not find a way to avoid it yet

**Comment by IvanProdaiko94** [comment]
@futuarmo I've fixed them) please take a look)

**Comment by futuarmo** [comment]
@IvanProdaiko94 I just tried vendor too and it's worked for me too) Ok, everything is good. Thanks for PR)

**Review by futuarmo — APPROVED** [review]

**Comment by HadesArchitect** [comment]
Congrats and thank you so much @IvanProdaiko94 @futuarmo

**Comment by HadesArchitect** [comment]
@IvanProdaiko94 If you would like to get certified as an Apache Cassandra Developer or an Administrator for free, let me know we sponsor these certifications. You definitely deserve it!

**Pull request merged**
